### ISSUE TITLE
Delete action on user endpoint

### ISSUE THREAD

**Issue by keawade** [garden-stream/garden#12]
Would allow a user to delete their account.

Would need to go through the deleting user's `following` collection and unfollow each user so the deleting user will be removed from the other user's `followers` collection.

**Comment by NathanBland** [comment]
This gets into cascading deletes, which I don't like the idea of, but is probably needed here.

https://docs.mongodb.com/v3.2/reference/method/db.collection.update/

Seems like the way to go here...

**Comment by NathanBland** [comment]
To add to this...

Do we want a hard delete, or do we want to mark a user as deleted, which would give them the option of recovering their account within a time frame?

**Comment by keawade** [comment]
Probably hard delete? At least for 1.0. We can save the soft delete for later if we care.

**Comment by NathanBland** [comment]
I think soft-delete is actually easier... Because then I don't have to do a cascading delete.

**Comment by keawade** [comment]
Isn't a soft delete just a delayed and potentially reversible hard delete?

**Comment by NathanBland** [comment]
Basically, I'd add a `Boolean` flag on the user that was `isDeleted`, and filter on it.

**Comment by keawade** [comment]
Sure but you still have to actually delete it.

**Comment by NathanBland** [comment]
Do you?

As far as anything else is concerned, your account is gone, but you can reactivate it.

**Comment by keawade** [comment]
You don't have too, but we probably should.
