### ISSUE TITLE
Paginate results

### ISSUE THREAD

**Issue by keawade** [garden-stream/garden#5]
We probably need to paginate results so when this grows to thousands or more of items/users returning from an endpoint we don't make our clients/server cry.

**Comment by NathanBland** [comment]
What are you purposing the initial return `limit` be? 10, 100, 1000? I'd like to keep it consistent for all the `endpoints`

**Comment by keawade** [comment]
Doesn't matter to me. Probably 10 is probably too low, 100 too high. 25 seems good?

**Comment by NathanBland** [comment]
Thinking about this more, I'll probably make it dynamic, with the ability to set your limiter, up to a certain amount.

**Comment by keawade** [comment]
Sounds good. A default value would be handy though.
