### ISSUE TITLE
User profile 

### ISSUE THREAD

**Issue by keawade** [garden-stream/garden#7]
A user should have something like the following route

* `PUT` or `POST`
  * `/user/:userid` expects a user object to update the stored user object.

**Comment by NathanBland** [comment]
The user could probably also see some enhancements as far as what lives on the object, but that's another issue.

**Comment by NathanBland** [comment]
After looking further, at the moment, there are actually no properties on the user object that I want to be changeable. 

What did you have in mind?

**Comment by keawade** [comment]
Users should probably have a unique id so they can change their username/displayname/email/whatever. Whatever those extra fields beyond unique id and password are, they should be changeable (probably).

**Comment by NathanBland** [comment]
Users do have a unique id, but for friendliness we do everything by username.. Which _could_ be changeable I suppose, it just adds to the chance that someone will forget their login information..
- I like the idea of a display name. 
- email doesn't currently exist in the user model, and as of now I don't see a need for one..
- a user description seems like a good candidate for this as well.

**Comment by keawade** [comment]
Email doesn't exist currently, but should if we want to be able to send out email alerts or compilations of recent content.

We need a unique identifier for navigation to their profile and also for a login username. These don't have to be the same field.

If we're masking usernames behind display names, do we want to navigate with usernames? I think we might want to use their user ids instead.

**Comment by NathanBland** [comment]
I think it is still best to navigate with username. Even if you can change your display name, username makes a nice constant, _and_ far nicer looking urls than `id`s

**Comment by keawade** [comment]
Okay so it looks like we've got this structure for users then:

```
{
  username: string;
  displayname: string;
  posts: Array<PostObject>;
  following: Array<UserObject>;
  followers: Array<UserObject>;
}
```

I think we should drop all but user name and display name when returning arrays of UserObjects or posting a UserObject.
